-- MySQL Script generated by MySQL Workbench
-- Sat Aug 12 13:08:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user_activity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_activity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_activity` DEFAULT CHARACTER SET utf8 ;
USE `user_activity` ;

-- -----------------------------------------------------
-- Table `user_activity`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`review` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `review` LONGTEXT NOT NULL,
  `rating` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `reference_type` ENUM('PRATILIPI', 'AUTHOR') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `state` ENUM('PUBLISHED', 'BLOCKED', 'DELETED') NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_type_reference_id_user_id` (`reference_type`,`reference_id`,`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_activity`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`vote` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` ENUM('LIKE', 'NONE') NOT NULL,
  `reference_type` ENUM('REVIEW', 'COMMENT') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_type_reference_id_user_id` (`reference_type`,`reference_id`,`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_activity`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `comment` LONGTEXT NOT NULL,
  `reference_type` ENUM('REVIEW') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `state` ENUM('ACTIVE', 'BLOCKED', 'DELETED') NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_activity`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`follow` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `reference_type` ENUM('AUTHOR') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `state` ENUM('FOLLOWING', 'UNFOLLOWED', 'IGNORED') NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_type_reference_id_user_id` (`reference_type`,`reference_id`,`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_activity`.`complain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`complain` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` ENUM('INAPPROPRIATE', 'VIOLATION') NOT NULL,
  `reference_type` ENUM('REVIEW', 'COMMENT') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `state` ENUM('OPEN', 'DELETED') NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_type_reference_id_user_id` (`reference_type`,`reference_id`,`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_activity`.`count_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_activity`.`count_lookup` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `reference_type` ENUM('PRATILIPI', 'AUTHOR', 'REVIEW', 'COMMENT') NOT NULL,
  `reference_id` VARCHAR(40) NOT NULL,
  `count_type` ENUM('RATE', 'REVIEW', 'COMMENT', 'LIKE', 'FOLLOW') NOT NULL,
  `count` INT UNSIGNED ZEROFILL NOT NULL,
  `date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `reference_type_reference_id_count_type` (`reference_type`,`reference_id`,`count_type`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
